// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBeKCh6sLgzCVOYE2NTQs4SjbH7g-1_wSw",
    appId: '1:173688729888:web:0597f0cdc973382adee745',
    messagingSenderId: '173688729888',
    projectId: 'chores-4725c',
    authDomain: 'chores-4725c.firebaseapp.com',
    storageBucket: 'chores-4725c.appspot.com',
    measurementId: 'G-TYJB66TRBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyA36ayUi6NE1N5Hmr78ZvrhoQozs4fyZx8",
    appId: '1:173688729888:android:5b0273ab6579a100dee745',
    messagingSenderId: '173688729888',
    projectId: 'chores-4725c',
    storageBucket: 'chores-4725c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCKyG0rKgtlYp2h3Fe3W7aoTK2cWMNqqlg",
    appId: '1:173688729888:ios:0ecb072ff84b31e8dee745',
    messagingSenderId: '173688729888',
    projectId: 'chores-4725c',
    storageBucket: 'chores-4725c.appspot.com',
    iosClientId:
        '173688729888-p0kiaemtugiu7smd9ouodcoqbvuvnbeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyCKyG0rKgtlYp2h3Fe3W7aoTK2cWMNqqlg",
    appId: '1:173688729888:ios:0ecb072ff84b31e8dee745',
    messagingSenderId: '173688729888',
    projectId: 'chores-4725c',
    storageBucket: 'chores-4725c.appspot.com',
    iosClientId:
        '173688729888-p0kiaemtugiu7smd9ouodcoqbvuvnbeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chores',
  );
}
