name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
  WEB_API_KEY: ${{ secrets.WEB_API_KEY }}
  ANDROID_API_KEY: ${{ secrets.ANDROID_API_KEY }}
  IOS_API_KEY: ${{ secrets.IOS_API_KEY }}

jobs:
  build_deploy_release:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: 📚 Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 📚 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 📚 Flutter Pub Get
        run: flutter pub get

      - name: 🐦 Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      - name: 🚀 Shorebird Patch
        id: shorebird-patch
        uses: shorebirdtech/shorebird-patch@v0
        with:
          release-version: 1.0.0+5
          args: --allow-native-diffs -- --no-tree-shake-icons
          platform: android

      - name: 📝 Output Patch Version
        run: echo ${{ steps.shorebird-patch.outputs.patch-number }}

      #- run: flutter build apk
      #- run: flutter build appbundle
      #- name: 🚀 GitHub Release
        #uses: ncipollo/release-action@v1
        #with:
          #artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          #tag: v0.1.${{ github.run_number }}
          #name: Chores v0.1.${{ github.run_number }}
          #token: ${{ secrets.TOKEN }}


      - name: 📚 Build Web Version
        run: flutter build web --wasm

      - name: 🚀 Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHORES_4725C }}
          channelId: live
          projectId: chores-4725c